# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be8c7fd3d345607e47d285e7f7d4be22ef62dc0caf5f56da660260d377371b6d1b27d65db1c1d871674092a14c7190f1b9e999f9fcfde34e7580d71326b5e0e3

test:
  secret_key_base: 136f0245d787ff94fee66507dc3765118fdab3aaf464f1aed9025922c6977b3f93bc09ebab9cc6b23d2aa16b9ffe78e16f64baccf510e95354311add929cea06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
